### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by zdyshine** [20151001860/Real_ESRGAN_paddle#1]
感谢大佬的开源，在运行的时候发现
models/sr_model.py的头文件中，

from .archs import build_network
from .base_model import BaseModel
没有对应的文件，方便 上传一下文件吗？

**Comment by 20151001860** [comment]
你好，感谢你的提醒，已经上传了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "20151001860/Real_ESRGAN_paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 上午9:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[20151001860/Real_ESRGAN_paddle] 缺少文件 (Issue #1)





 
感谢大佬的开源，在运行的时候发现
 models/sr_model.py的头文件中，
 
from .archs import build_network
 from .base_model import BaseModel
 没有对应的文件，方便 上传一下文件吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zdyshine** [comment]
> 你好，感谢你的提醒，已经上传了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "20151001860/Real_ESRGAN_paddle" ***@***.***&gt;; 发送时间:&nbsp;2021年12月11日(星期六) 上午9:23 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[20151001860/Real_ESRGAN_paddle] 缺少文件 (Issue #1) 感谢大佬的开源，在运行的时候发现 models/sr_model.py的头文件中， from .archs import build_network from .base_model import BaseModel 没有对应的文件，方便 上传一下文件吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

感谢，我试一下，没问题了我这边star，然后关闭issue哈。

**Comment by zdyshine** [comment]
已经成功运行了，但是发现loss非常大，1e9这样数值的损失，请问有什么解决办法吗？

**Comment by 20151001860** [comment]
你说的是什么损失，我没有遇到这么大的。

**Comment by zdyshine** [comment]
> 你说的是什么损失，我没有遇到这么大的。

我用的RCAN的网络结构，仅用L1损失函数进行训练。我刚刚试了把RCAN网络里面的模块数减少，能正常训练，初始loss在0.3左右。但是网络结构一增大，损失就变的非常大了。

**Comment by 20151001860** [comment]
RCAN?我这没用RCAN，这我就不知道了。

**Comment by zdyshine** [comment]
> RCAN?我这没用RCAN，这我就不知道了。

好的,了解，请问一下您有加载pytorch版本的Real_ESRGAN的预训练模型吗?

**Comment by 20151001860** [comment]
抱歉没有



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月11日(星期六) 下午5:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [20151001860/Real_ESRGAN_paddle] 缺少文件 (Issue #1)





  
RCAN?我这没用RCAN，这我就不知道了。
  
好的,了解，请问一下您有加载pytorch版本的Real_ESRGAN的预训练模型吗?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
